# Generated by Django 5.2 on 2025-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulSources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='note_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sources',
            name='note_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('link', 'Link'), ('file', 'File'), ('note', 'note')]),
        ),
    ]
