# Generated by Django 5.2 on 2025-05-27 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('codeLibrary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_fragments', to='codeFragments.codelibrary')),
            ],
        ),
        migrations.AddConstraint(
            model_name='codelibrary',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='unique_user_language'),
        ),
        migrations.AddConstraint(
            model_name='codefragment',
            constraint=models.UniqueConstraint(fields=('codeLibrary', 'title'), name='unique_codeLibrary_title'),
        ),
    ]
